### ISSUE TITLE
Simple typo: 1080p, 16:9, not equal to 1920x1080

### ISSUE THREAD

**Issue by ofernandofilo** [rdp/screen-capture-recorder-to-video-windows-free#102]
Code: ResolutionOptions` = {'native input (unscaled)' => nil, 'vga' => '640x480', 'svga' => '800x600', 'xga' => '1024x768', 'PAL' => '768x576', 'hd720' => '1280x720', 'hd1080' => '1980x1080'}	

I don't know what the code do, but it does not look right to me:
'hd1080' => '19**8**0x1080'

It should be:
'hd1080' => '19**2**0x1080'

Right?

source: https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/864de525b38720dc75a867da283a57309a01ba74/configuration_setup_utility/record_with_buttons_options_pane.rb#L19

**Comment by rdp** [comment]
Good catch!

On Monday, December 4, 2017, Fernando Di Ramos <notifications@github.com>
wrote:
> Code: ResolutionOptions` = {'native input (unscaled)' => nil, 'vga' =>
'640x480', 'svga' => '800x600', 'xga' => '1024x768', 'PAL' => '768x576',
'hd720' => '1280x720', 'hd1080' => '1980x1080'}
>
> I don't know what the code do, but it does not look right to me:
> 'hd1080' => '1980x1080'
>
> It should be:
> 'hd1080' => '1920x1080'
>
> Right?
>
> source:
https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/864de525b38720dc75a867da283a57309a01ba74/configuration_setup_utility/record_with_buttons_options_pane.rb#L19
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/_29a8Rtl5D8DxTJ9ZkECq4PW6m3LE3CbmkR_6FJC_YIdJYUGtlOoELMDaW243JImITO2drRloWMlGgAZYN7s8YMGw4U2EV7OFz7kl2tD8GUjDDUvCCpcZTHm0_e80ijDiertOZdUbbUmUIfWVHtHrRS3ju80Kw=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0HXkZNySpeCcbOq9LAz1q2QGpI4jks5s89IHgaJpZM4Q0ej_.gif>

**Comment by rdp** [comment]
hopefully fixed in cbb2a1c00fe3f01e3be6aad6a419975e2981e0e2
