### ISSUE TITLE
How to record both audio source(virtual-audio-capturer) and my USB microphone

### ISSUE THREAD

**Issue by ju1ce232** [rdp/screen-capture-recorder-to-video-windows-free#119]
Hello,

I'm able to select only one source, either virtual-audio-capturer) or my Headset Microphone but actually want to record not only audio but my voice too. Please help me to configure it so.
I see this config:
ffmpeg.exe -y -rtbufsize 150M -f dshow -framerate 30 -i video="screen-capture-recorder":audio="virtual-audio-capturer" -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac -strict -2 -ac 2 -b:a 128k "output.mp4"
And have this one for microphone:
audio="Headset Microphone (Jabra EVOLVE 20 MS)
Can't combine them. Please help me :)

Thanks,
Sergey.

**Comment by rdp** [comment]
there's a way to do it with the "amix" filter I believe.  Anyway you'll
have two dshow inputs like -f dshow -i audio=virtual-audio-capturer -f
dshow -i audio=my-other-microphone and then have the mix the two... :)

**Comment by ju1ce232** [comment]
I apologize in so long delay with my feedback but still can't manage to work both the audio sources together. I tried like this:
-y -rtbufsize 150M -f dshow -i audio="virtual-audio-capturer" -f dshow -i audio="Headset Microphone (Jabra EVOLVE 20 MS)" -f dshow -framerate $fps$ -i video="screen-capture-recorder" -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac -strict -2 -ac 2 -b:a 128k "$output$"

Also, this:
-i audio="virtual-audio-capturer":audio="Headset Microphone (Jabra EVOLVE 20 MS)"

Sorry, I didn't get how to mix them :(

**Comment by rdp** [comment]
Did you try the amix filter? It there's another that does the same thing
hmm...

On Monday, December 24, 2018, ju1ce232 <notifications@github.com> wrote:
> I apologize in so long delay with my feedback but still can't manage to
work both the audio sources together. I tried like this:
> -y -rtbufsize 150M -f dshow -i audio="virtual-audio-capturer" -f dshow -i
audio="Headset Microphone (Jabra EVOLVE 20 MS)" -f dshow -framerate $fps$
-i video="screen-capture-recorder" -c:v libx264 -r $fps$ -preset ultrafast
-tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac
-strict -2 -ac 2 -b:a 128k "$output$"
>
> Also, this:
> -i audio="virtual-audio-capturer":audio="Headset Microphone (Jabra EVOLVE
20 MS)"
>
> Sorry, I didn't get how to mix them :(
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/oy-uJ0pBPXvGMyUey13gBCokRp_z8xp7VCwNJ7cSHpORx3vZTMpyVqpzghGijsNAEabBV7fm0C7ixAmGL4zl2_gWrrXNuESWqSmJFGtfi0qMLrdPQow0TuLTseD_Gax9ukE6RQc7QbpbcTvwhZ2P-ojpww=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0FtpC-lmxDGWb37Q0xa7fYJwF6tqks5u8KJAgaJpZM4ZTwke.gif>

**Comment by ronitosan** [comment]
@ju1ce232 Hey man, could i see the screenshot of your ShareX - Screen recording options on this. This is what i need as well. audio for my Jabra USB headset and the pc sound. Thank you so much!

**Comment by omer-re** [comment]
After adjusting this suggestion, I was able to change ShareX screen recording command to the following:

```
-rtbufsize 150M -f gdigrab -framerate $fps$ -offset_x $area_x$ -offset_y $area_y$ -video_size $area_width$x$area_height$ -draw_mouse $cursor$ -i desktop -f dshow -i audio="virtual-audio-capturer" -f dshow -i audio="Microphone Array (Realtek High Definition Audio(SST))" -filter_complex amix=inputs=2:duration=first:dropout_transition=3 -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a libmp3lame -qscale:a 4 -y "$output$"
#works well, recording both audio channels and right region of video.
```

Which worked well on my machine, allows me to record the right region of the screen plus multiple audio channels simultaneously. 

Task settings> Capture > screen recorder > screen recorder options> check on "use custom commands" then paste it there.
[should look like this](https://i.imgur.com/vwlK29Z.png)

**Comment by FalconCreates** [comment]
I tried to edit the code below, but unfortunately it does not work for me...  😢 I use the latest version of **Setup.Screen.Capturer.Recorder.v0.12.1**. My microphone is **Shure MV7**. 
### How to improve the code to record sound from the microphone and the desktop at the same time?

- The code I have tested, which generates an error.
`-rtbufsize 150M -f gdigrab -framerate $fps$ -offset_x $area_x$ -offset_y $area_y$ -video_size $area_width$x$area_height$ -draw_mouse $cursor$ -i desktop -f dshow -i audio="virtual-audio-capturer" -f dshow -i audio="Microphone (2- Shure MV7)" -filter_complex amix=inputs=2:duration=first:dropout_transition=3 -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a libmp3lame -qscale:a 4 -y "$output$"`

- Screen my settings
![d64qYD7qal](https://user-images.githubusercontent.com/13267505/104186478-c1a8a200-5416-11eb-8e98-dec49a53bd4b.png)
- Code test in console
![msipstZxs0](https://user-images.githubusercontent.com/13267505/104186512-ce2cfa80-5416-11eb-8c54-93bc18fc3fe8.png)
- Screen of an error that occurs during recording
![WXXhTHYItN](https://user-images.githubusercontent.com/13267505/104186539-d71dcc00-5416-11eb-82d1-0cc27f549e9b.png)

**Comment by omer-re** [comment]
>     * e MV7)" -filter_com

not sure, but it looks like the error is caused by the region you are trying to record.
is it happening if you choose a (relatively)  small rectangle in the middle of the screen?

**Comment by rdp** [comment]
Gdigrab works ok without the audio , as is?

On Monday, January 11, 2021, Omer Re <notifications@github.com> wrote:
> * e MV7)" -filter_com
>
> not sure, but it looks like the error is caused by the region you are
trying to record.
> is it happening if you choose a (relatively) small rectangle in the
middle of the screen?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/9u0Axzz1Ytylw_M5LrCDxLMhuvAM9-TaGL0TH1uLiIbA9rC4zzZvI0QKaD8DZ2YQSfcMC8OXWP-SgaJHRlvSqPubYhPkCYirOeADYF232LVAApgb6uKe6PBz3ZxWlEhWm4DFCFzoZiXbFMY6_ToYT5_oAZtbUdyMg8SzP9DAdvdWZC4b0sNIE5ICjUCrnmRatVeiZ6VJOLIMaJaelszPSdk27tQ8qZ1vtupCryN7mg=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUBZOJZI5NJU7M7FU2TSZNERVA5CNFSM4GKPBEPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFUYKK6I.gif>

**Comment by FalconCreates** [comment]
> > ```
> > * e MV7)" -filter_com
> > ```
> 
> not sure, but it looks like the error is caused by the region you are trying to record.
> is it happening if you choose a (relatively) small rectangle in the middle of the screen?

Actually on small areas of the screen it works! Nice! 😃 In the tests I did I tried catching the whole monitor in 4k. The most important goal was achieved. Thank you. ❤️
I have one more, but less important question. What can I do to be able to record the whole screen in 4k? As I mentioned, currently an error pops up when trying to record.

**Comment by rdp** [comment]
Check your boundaries or maybe there is a full screen option?

On Wednesday, January 13, 2021, Michal <notifications@github.com> wrote:
> * e MV7)" -filter_com
>
> not sure, but it looks like the error is caused by the region you are
trying to record.
> is it happening if you choose a (relatively) small rectangle in the
middle of the screen?
>
> Actually on small areas of the screen it works! Nice! 😃 In the tests I
did I tried catching the whole monitor in 4k. The most important goal was
achieved. Thank you. ❤️
> I have one more, but less important question. What can I do to be able to
record the whole screen in 4k? As I mentioned, currently an error pops up
when trying to record.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/LyTrlIT6NiEzlrrBrRK99bJ7BEL7YXUwYHjX6ldmIrHtxo5jnCJzpQ-GEcb3_ykbvtx7TeirO1ChOycoPVOMld2E950-RyRmA4dp1M_4dUFGCuQrxTOEPIe32ellVYNSDfYEctkHmbmQhDR3nDPVaLBSO-JGruKW1x6nlHWcl5unDiQTHEXOQP38f7wih1_kQDmFGKKbFMOF1kEvbfCvyi2Wbp2eJZRoU4QFaTna0g=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUACBZJ4YR34NLYWG7DSZVKAJA5CNFSM4GKPBEPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFVA44LY.gif>

**Comment by directorcrow** [comment]
this might word for you   https://www.youtube.com/watch?v=ysiAEbWox4k
So I can't get the workaround to work but you can use windows to your advantage. So to get this to work ShareX should be set to Virtual audio and then go to your desktop and right-click the SOUND ICON at the bottom of your screen and click SOUNDS then you click on RECORDING and click on your microphone and click PROPERTIES then click LISTEN then click on LISTEN TO THIS DEVICE then click on PLAY THROUGH THIS DEVICE and then in the dropdown menu select DEFAULT PLAYBACK DEVICE and then you can click ok. Do some tests and use the sound mixer to adjust the volume. works for me with the right tweaking and if you do it right you should not go crazy.😁

**Comment by rdp** [comment]
Any luck?

**Comment by movsar** [comment]
This works for me like magic!
`-i video="screen-capture-recorder" -f dshow -i audio="Microphone (Realtek(R) Audio)"  -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2 `

Microphone (Realtek(R) Audio) - is my selected microphone device name

**Comment by rdp** [comment]
Yeah it doesn't support more than one audio/video at the moment, funding or
PR welcome :)

**Comment by Geczy** [comment]
can confirm it works, so using sharex my command line is like this

![image](https://user-images.githubusercontent.com/1036968/227280136-33c2cfeb-b1e0-497f-aae0-44d8e7e10b19.png)


```bash
-hide_banner -f dshow -thread_queue_size 1024 -rtbufsize 256M -audio_buffer_size 80 -framerate $fps$ -i video="screen-capture-recorder" -f dshow -i audio="Microphone (NVIDIA Broadcast)" -f dshow -i audio="virtual-audio-capturer" -filter_complex amix=inputs=2 -c:v libx264 -r $fps$ -preset ultrafast -tune zerolatency -crf 28 -pix_fmt yuv420p -movflags +faststart -c:a aac -ac 2 -b:a 128k -y "$output$"
```
