### ISSUE TITLE
Captures windows in the foreground

### ISSUE THREAD

**Issue by IsMaix** [rdp/screen-capture-recorder-to-video-windows-free#129]
This application is already amazing and it already has the ability to not capture the mouse cursor so thats good, but is there any way to only capture one specific window so you cant see the stuff in the foreground, kind of like the window capture feature in obs. Or do you plan to update the app so it will have this feature?

**Comment by sylvio-ruiz** [comment]
Yes, there is. But the registry utility tools hasn't this option.
I will write a new utility tool in pascal and release the source code to find the HWND from a Window using its title name and update the registry with its value like Obs.

These are the values that must be writed to the registry key before you run the capture device:
hwnd_to_track (this captures only the client area)
hwnd_to_track_with_window_decoration (this captures the entire window).

**Comment by dextella** [comment]
Any progress on HWND tracking?  I would request tracking by window title as well.
Thanks

**Comment by IsMaix** [comment]
> Any progress on HWND tracking? I would request tracking by window title as well.
> Thanks

Hey sorry I've moved on as I found a better solution for my issue.
