### ISSUE TITLE
Is there a way to temporarily disable the virtual camera ?

### ISSUE THREAD

**Issue by beppe9000** [rdp/screen-capture-recorder-to-video-windows-free#146]
I want to only show my physical webcam in google chrome when webpages ask for camera permission. Thanks

**Comment by rdp** [comment]
You Can unregister the dll...

On Thursday, January 14, 2021, beppe9000 <notifications@github.com> wrote:
> I want to only show my physical webcam in google chrome when webpages ask
for camera permission. Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/HYxmnszh8MT7jHTUZcM_PtFUDSzem0oENrrjeoSk-EK2lHYhS6gQ4ORd5MkFi2LJSQvZC_PPGGlsWrcdzBK5TeDVYmObh1W55k5pb5dXAKi4iesE0XMq1LKAY0J9UnKzr9Y2Rl66NyW6miw-ar44YWBtJRXBiNADQH1a8q4YFAqw0XmjlnQhtoGqujilJ81mjZ_GJvg6dCrGsYwJ2ywOotOy7zA=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUD25YI36H5G6TCWOWTSZ54JLA5CNFSM4WDHIX3KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LW7XGHA.gif>

**Comment by beppe9000** [comment]
thanks. i think i can use sysinternal autoruns fro that
