### ISSUE TITLE
Minimum requirements for  screen-capture-recorder?

### ISSUE THREAD

**Issue by bitov27** [rdp/screen-capture-recorder-to-video-windows-free#150]
Hi! I want to know what the minimum hardware requirements for screen-capture-recorder ? Does it possible to record screen on VPS Windows? Thanks a lot.

**Comment by rdp** [comment]
You could adjust fps down I suppose.
Haven't tried it in rdp might work

On Wednesday, April 14, 2021, bitov27 ***@***.***> wrote:
> Hi! I want to know what the minimum hardware requirements for
screen-capture-recorder ? Does it possible to record screen on VPS Windows?
Thanks a lot.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/_u8CDB7qONwMvxfarWJFWPs-MAlVqUpdXOclDQPFnf7XbCNxJ8GfX05NL8g4HHb-viwM0ox5_Z2bHGaJfCukCXX-ydbxuFidSDR-h9EwwZdQ4h4RNqL8VufEe7pV1FB51CFpFBqwP5-Q0UpI73LfH2VwGpdbu7IXkF4m6CvmOSWhRhys6pJK4B8K8JQVm1JNZvT5jTIh8HmnYji0cSpr46wtPnM=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUC53RGAB7ZFRAFDVT3TIU6KXA5CNFSM424Y63P2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4MY54VVQ.gif>

**Comment by rdp** [comment]
Should run anywhere with proper config settings for ffmpeg, albeit slowly.  x264 has a superfast option etc.
