### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by saweisulzer** [rdp/screen-capture-recorder-to-video-windows-free#158]
After pressing Stop button the recording doesn't stops anymore. ffmpeg.exe continues to run, have to kill it and the file is corrupted afterwards.

2022-07-05T16:48:52.335+02:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
C:/Program Files (x86)/Screen Capturer Recorder/configuration_setup_utility/vendor/sane-0.25.5/lib/sane/irb_startup_options.rb:4: warning: encountered \r in middle of line, treated as a mere space
C:/Program Files (x86)/Screen Capturer Recorder/configuration_setup_utility/jruby-swing-helpers/lib/simple_gui_creator/ffmpeg_helpers.rb:21: warning: `+' after local variable or literal is interpreted as binary operator
C:/Program Files (x86)/Screen Capturer Recorder/configuration_setup_utility/jruby-swing-helpers/lib/simple_gui_creator/ffmpeg_helpers.rb:21: warning: even though it seems like unary operator
starting version 0.12.12
writing to file: C:\Users\xxx\Videos\Captures/5.mp4
about to run ffmpeg -loglevel info   -f dshow  -video_device_number 0 -i video="screen-capture-recorder"  -f dshow -audio_device_number 0 -i audio="Kopfhörermikrofon (Plantronics Blackwire 3220 Series)"  -f dshow -audio_device_number 0 -i audio="virtual-audio-capturer"  -f dshow -audio_device_number 0 -i audio="Microphone Array (AMD Audio Device)"  -filter_complex amix=inputs=3  -vcodec libx264  -pix_fmt yuv420p -s 1920x1080 -preset ultrafast -vsync vfr -acodec libmp3lame  -f mp4 "C:\Users\xxx\Videos\Captures/5.mp4"
warning: thread "Ruby-0-Thread-1: C:/Program Files (x86)/Screen Capturer Recorder/configuration_setup_utility/jruby-swing-helpers/lib/simple_gui_creator/swing_helpers.rb:64" terminated with exception (report_on_exception is true):
Errno::ESRCH: No such process - No message available
                                   kill at org/jruby/RubyProcess.java:1391
                                   kill at org/jruby/RubyProcess.java:1343
                  wait_for_ffmpeg_close at C:/Program Files (x86)/Screen Capturer Recorder/configuration_setup_utility/jruby-swing-helpers/lib/simple_gui_creator/ffmpeg_helpers.rb:66
  start_recording_with_current_settings at record_with_buttons.rb:220
Exception in thread "Ruby-0-Thread-1: C:/Program Files (x86)/Screen Capturer Recorder/configuration_setup_utility/jruby-swing-helpers/lib/simple_gui_creator/swing_helpers.rb:64" java.lang.NullPointerException: Cannot invoke "org.jruby.runtime.ThreadContext.getThread()" because "this.mainContext" is null
        at org.jruby.internal.runtime.ThreadService.getMainThread(ThreadService.java:233)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1822)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.base/java.lang.Thread.run(Unknown Source)
ffmpeg version N-44080-gdfb4757 Copyright (c) 2000-2012 the FFmpeg developers
  built on Aug 31 2012 16:58:51 with gcc 4.7.1 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-pthreads --enable-runtime-cpudetect --enable-avisynth --enable-bzlib --enable-frei0r --enable-libass --enable-libcelt --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libopenjpeg --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libutvideo --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      51. 70.100 / 51. 70.100
  libavcodec     54. 55.100 / 54. 55.100
  libavformat    54. 25.104 / 54. 25.104
  libavdevice    54.  2.100 / 54.  2.100
  libavfilter     3. 15.101 /  3. 15.101
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
[dshow @ 04ae1140] Estimating duration from bitrate, this may be inaccurate
Input #0, dshow, from 'video=screen-capture-recorder':
  Duration: N/A, start: 21249.060000, bitrate: N/A
    Stream #0:0: Video: rawvideo, bgra, 1934x1094, 30 tbr, 10000k tbn, 30 tbc
[dshow @ 04ae1140] real-time buffer 556% full! frame dropped!
    Last message repeated 15 times
[dshow @ 04aed1e0] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for  Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=Kopfh├Ârermikrofon (Plantronics Blackwire 3220 Series)':
  Duration: N/A, start: 21249.118000, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
[dshow @ 04ae1140] real-time buffer 556% full! frame dropped!
    Last message repeated 1 times
[dshow @ 04b60f60] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for  Input Stream #2.0 : stereo
Input #2, dshow, from 'audio=virtual-audio-capturer':
  Duration: N/A, start: 21249.705000, bitrate: 1536 kb/s
    Stream #2:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[dshow @ 04ae1140] real-time buffer 556% full! frame dropped!
    Last message repeated 18 times
[dshow @ 0203a500] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for  Input Stream #3.0 : stereo
Input #3, dshow, from 'audio=Microphone Array (AMD Audio Device)':
  Duration: N/A, start: 21249.845000, bitrate: 1411 kb/s
    Stream #3:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
[dshow @ 04ae1140] real-time buffer 556% full! frame dropped!
[libx264 @ 0cd8b080] using cpu capabilities: MMX2 SSE2Fast SSSE3 FastShuffle SSE4.2 AVX AVX2 FMA3 SSEMisalign LZCNT BMI1 BMI2
[libx264 @ 0cd8b080] profile Constrained Baseline, level 4.0
[libx264 @ 0cd8b080] 264 - core 125 r2208 d9d2288 - H.264/MPEG-4 AVC codec - Copyleft 2003-2012 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'C:\Users\xxx\Videos\Captures\5.mp4':
  Metadata:
    encoder         : Lavf54.25.104
    Stream #0:0: Audio: mp3 (i[0][0][0] / 0x0069), 44100 Hz, stereo, flt
    Stream #0:1: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080, q=-1--1, 10000k tbn, 30 tbc
Stream mapping:
  Stream #1:0 (pcm_s16le) -> amix:input0 (graph 0)
  Stream #2:0 (pcm_s16le) -> amix:input1 (graph 0)
  Stream #3:0 (pcm_s16le) -> amix:input2 (graph 0)
  amix (graph 0) -> Stream #0:0 (libmp3lame)
  Stream #0:0 -> #0:1 (rawvideo -> libx264)
Press [q] to stop, [?] for help
[dshow @ 04ae1140] real-time buffer 556% full! frame dropped!
button cancelled somehow!No such process - No message available Stop RubyProcess.java:1391 RubyProcess.java:1343
button cancelled somehow!No such process - No message available Stop RubyProcess.java:1391 RubyProcess.java:1343
frame= 1373 fps= 27 q=13.0 size=   16214kB time=00:00:50.53 bitrate=2628.5kbits/s

**Comment by saweisulzer** [comment]
when trying to press button 'Configure screen recorder bounds box':

dummy: Immediate exit requested
button cancelled somehow!cannot load Java class com.sun.awt.AWTUtilities Configure screen recorder bounds box JavaClass.java:292 JavaClass.java:288
button cancelled somehow!cannot load Java class com.sun.awt.AWTUtilities Configure screen recorder bounds box JavaClass.java:292 JavaClass.java:288

**Comment by rdp** [comment]
what java version?

**Comment by rdp** [comment]
OK hopefully fixed for JRE > 8 with latest.
