### ISSUE TITLE
Why save settings to the registry instead of a config file?

### ISSUE THREAD

**Issue by Savasdotexe** [rdp/screen-capture-recorder-to-video-windows-free#163]
I'm guessing there's a reason why, hence the question, but I can't see it and for me personally having the config/settings in the registry is a pain.

As per the readme on the main page it says you can create an ini file called "ScreenCaptureRecorder.ini", however it reads the registry first.. Why not have a master config file in the installation folder to read or choose where to read it first in that case? This way would allow a portable version to be created in addition.

**Comment by rdp** [comment]
That's weird, I responded via email but it didn't show up.
Anyway I said:
It reds the ini file first.  I am thinking of changing it so that if the .ini file exists, it ignores the registry... :)

And in v0.12.3 I changed it so if ini file exists, it only reads from it.

Cheers!
