### ISSUE TITLE
Can't load audio device

### ISSUE THREAD

**Issue by shakiare** [rdp/screen-capture-recorder-to-video-windows-free#168]
When i launch "select audio devices" pane get an error and load only first input device in checkbox list

Error:
"[\u2713:choose_audio_0] \"IN 1-2 (BEHRINGER UMC 404HD 192k) \""
button cancelled somehow!undefined method `delete' for nil:NilClass Select audio devices record_with_buttons_options_pan
e.rb:236 swing_helpers.rb:258

![Immagine](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/assets/137221599/1748a25c-d1ab-4ad7-b30e-43ac6987c5a0)

**Comment by shakiare** [comment]
After given a look at ruby code and make some mess in record_with_buttons.rb, now it works.

I have modified "if condition" at line 281, in a straight-ahead TRUE
"def bootstrap_devices
	if(1)..."
During first execution with if-mods on, i have selected some input sources and saved the configuration.
Now i have restored if condition at line 281 
"if(!video_device && !audio_devices_or_nil)..."
 and everything works well too.

**Comment by rdp** [comment]
Hmm it seems the config was in a weird state?  Do you remember how you got here?  Was there an aborted first run or something?  Do you have steps to repro the issue?  Did you manually uninstall virtual-audio-capturer or does it not show up in the audio list?

**Comment by shakiare** [comment]
- Do you remember how you got here? 
Yes, i think it's my fault: i did a lot of mess with audio driver of an external sound card.

- Was there an aborted first run or something? 
There wasn't any aborted run or quite similar error...

Do you have steps to repro the issue? 
No, different tries but  i couldn't reproduce the issue. I have tried to completely unistall screen capturer recorder and reinstall it, but no more issue

Did you manually uninstall virtual-audio-capturer or does it not show up in the audio list?
i have installed virtual-audio-capturer after the issue. At first i thought that error was virtual-audio-capturer, so installed the virtual driver. But the issue was always there

It doesnt depend on installer/software bug: thereis something messed with my audio driver(s) configuration (2 different sound cards installed + some realtek audio control software)

**Comment by rdp** [comment]
OK if you nuke %HOMEPATH%/.sensible_cinema_storage folder can you repro?
I might have found a small path that could have the issue, but for a normal
install it should not have happened I don't think, I assume you ran into
this issue immediately after install?
Thanks!

**Comment by shakiare** [comment]
Nuked. It still works correctly. 
I have tried to delete folder, unistall and put a fresh installation. It works. I cant reproduce the isssue

**Comment by rdp** [comment]
OK thanks for trying :)
