### ISSUE TITLE
real-time buffer 276% full! frame dropped!

### ISSUE THREAD

**Issue by pengqiuyuan** [rdp/screen-capture-recorder-to-video-windows-free#37]
Hello, desktop capture, video is very good, audio will frame dropped!

ffmpeg -f dshow -i video="screen-capture-recorder":audio="virtual-audio-capturer" -vf scale=-1:480 -vcodec libx264 -r 60.97 -acodec libvo_aacenc  -vbr 3 -ac 2 -ar 44100 -ab 1900 -pix_fmt yuv420p -tune zerolatency -preset ultrafast -f flv "rtmp://192.168.1.50/hls/test"

**Comment by hamletmun** [comment]
Did you try to increase the following registry values?

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AFD\Parameters]
 "DefaultReceiveWindow"=dword:00010000
 "DefaultSendWindow"=dword:00010000
```

http://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=657&start=60#p5527

**Comment by Palak92** [comment]
I found the same issue in this command line-:
`ffmpeg -f dshow -i video="screen-capture-recorder" -vcodec libx264 -tune zerolatency -b:v 900k -f mpegts  http://localhost:8090`

error
```

>  Stream #0:0: Video: rawvideo, bgr0, 1920x1080, 30 fps, 30 tbr, 10000k tbn, 10000k tbc
> [dshow @ 000000000249a8a0] real-time buffer [screen-capture-recorder] [video input] too full or near too full (545% of size: 3041280 [rtbufsize parameter])! frame dropped!
>     Last message repeated 284 times
> http://localhost:8090: Unknown error
> [dshow @ 000000000249a8a0] real-time buffer [screen-capture-recorder] [video input] too full or near too full (545% of size: 3041280 [rtbufsize parameter])! frame dropped!
```

**Comment by rdp** [comment]
This is not an error it just implies you're not able to encode at realtime
so it drops some incoming packets.

**Comment by Palak92** [comment]
Can you please guide me what kind of encoding I should use in real-time to stream video?

**Comment by rdp** [comment]
I attempted to put some better examples here:
https://trac.ffmpeg.org/wiki/StreamingGuide

**Comment by Palak92** [comment]
I read them.. But no success.

- [ ] 1. like I tried `$ ffmpeg -y -loglevel warning -f dshow -i video="screen-capture-recorder" -vf crop=690:388:136:0 -r 30 -s 962x388 -threads 2 -vcodec libx264 -vpre baseline -vpre my_ffpreset -f flv rtmp:///live/myStream.sdp` but It said `File for preset 'baseline' not found`   

- 2. Then I tried streaming a video by http using-:
`ffmpeg -f mp4 --video_size 320x240 -r 25 -i screen-capture.mp4  http://localhost:8090/feed1.mp4`
But it gave error 
```
Unrecognized option '-video_size'.
Error splitting the argument list: Option not found
```

**Comment by rdp** [comment]
Read through that link carefully.  Once you have tried everything on it,
let me know...

**Comment by Palak92** [comment]
Hi, I went through the examples thoroughly.  I am getting "unknown" error.
command line:` ffmpeg -re -i out3.mp4 -c copy -f mpegts http://localhost:8080`
error: ```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'out3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.73.100
  Duration: 00:02:17.40, start: 0.000000, bitrate: 547 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1920x1080, 546 kb/s, 10 fps, 10 tbr, 10240 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
http://localhost:8080: Unknown error
```

**Comment by rdp** [comment]
The normal documentation may be helpful:
https://ffmpeg.org/ffmpeg.html
Basically the last thing listed is where it is "sending to" and you don't
have a receiving server to receive it there.
GL.

**Comment by Palak92** [comment]
I am sending it to  `http://localhost:8080` which is valid server. Why ffmpeg is not supporting it?

**Comment by rdp** [comment]
running with -loglevel debug might be helpful.  Unfortunately I'm not much
help, maybe try on the ffmpeg-user mailing list, good luck!

**Comment by Palak92** [comment]
I will look into that.
Thank you fo your time
