### ISSUE TITLE
Encoding doesn't start until audio is outputted, A/V horribly out of sync

### ISSUE THREAD

**Issue by mzso** [rdp/screen-capture-recorder-to-video-windows-free#51]
When I have "virtual-audio-capturer" as the audio source ffmpeg won't start encoding until something outputs audio. I just get a freezframe until that. And since the audio starts playing instantly instead of when the actually recording started it will get horribly out of sync.
With other audio sources like "Stereo Mix (ASUS Xonar D1 Audio Device)" or without audio this doesn't happen.

**Comment by rdp** [comment]
hopefully fixed with 0.12.9.  3 years later woot! :)
