### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by mid0ri** [rdp/screen-capture-recorder-to-video-windows-free#54]
I've been trying out your screen capture recorder and it works pretty well. Although i've realize that i can use vlc to do the samething so I was wondering how to remove your program from my pc? there's no uninstall! oh never mind i'm just being a dumb butt i see it :3

**Comment by rdp** [comment]
There should be an uninstall link in start men -> screen capture recorder
or using the standard way from control panel "remove program"
HTH.
-r

**Comment by rdp** [comment]
I think this works

**Comment by sergeevabc** [comment]
Issue should be re-opened as uninstall procedure is currently broken.

![](https://images.vfl.ru/ii/1514114140/7cfa26bb/19900711.png)

**Comment by sergeevabc** [comment]
Err… @rdp, hello?

**Comment by rdp** [comment]
Did you install multiple versions? That is some kind of innosetup failure
message...

On Wed, Dec 27, 2017 at 1:07 AM, Aleksandr Sergeev <notifications@github.com

**Comment by sergeevabc** [comment]
@rdp, I had a slightly older version (shipped with ShareX) installed, then downloaded and installed a newer one from your repository. It is the common routine to update any piece of software: a newer installer takes a proper care about older files and settings if finds them. But in your case it’s broken.

**Comment by rdp** [comment]
That's odd, you'd think that registering them both the latter would
"override"
I don't know much about shareX, nor does my installer, apparently.
Cheers!

**Comment by sergeevabc** [comment]
Have you actually tried to un-install Screen Capture Recorder yourself ever?
