### ISSUE TITLE
Recording the video streaming while browser is using same camera

### ISSUE THREAD

**Issue by Shadanana** [rdp/screen-capture-recorder-to-video-windows-free#55]
Hi,

I am trying to record a video stream coming from my USB web cam using your solution.Its working fine.

When browser (chrome) is using same USB webcam for some other video calling purpose (WebRTC) and if i try to record same stream (USB webcam)  your application will hang and dose not give any output.

Can you please tell me how to fix this issue...

Thank you,
Shadanana

**Comment by rdp** [comment]
http://betterlogic.com/roger/2013/05/directshow-webcam-splitter/ is about all I know on the subject, sorry it's not an easy one. Cheers!
