### ISSUE TITLE
Some release tags missing

### ISSUE THREAD

**Issue by leif81** [rdp/screen-capture-recorder-to-video-windows-free#61]
I was looking to download an older release that I saw listed in the `ChangeLog.txt`, but several of the newer releases ( >0.10) aren't showing up in the GitHub releases view:

https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases

I don't think it'd be too hard for me to find what I need by reviewing the git history, but it'd be convenient to have them officially tagged. 

I think all that needs to be done is go back and `git tag` them and they'll appear?

**Comment by rdp** [comment]
the latest version is 0.12.8...I'm not even sure how those other releases were tagged before LOL.  Do you need previous versions for anything in particular?

**Comment by leif81** [comment]
I don't think I will need an older version after all.

What had happened was I had gone to the GitHub releases section and saw what looked like the latest was 0.10 so I downloaded that. But then I was reading the `ChangeLog.txt` on master and realized there had been many releases since then. So instead I just downloaded the latest `screen-capture-recorder.dll` from master branch.

Perhaps if just the newest release, 0.12.8, is tagged that might help people like me grab the right one. I believe GitHub turns tags into releases sometimes for free which is probably why the older tags showed up there.

**Comment by Walkman100** [comment]
the [releases](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases) and [tags](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/tags) pages are identical...

**Comment by leif81** [comment]
@Walkman100 Ya they are. I think you missed the point :)

What I was proposing is that @rdp go bakc and add git tags for the recent releases (0.10 -> 0.12). Then each of those would show up in both the releases and tags pages.

**Comment by rdp** [comment]
Yeah but I don't know how useful they'd be without the release executables...however I did start using github releases just now, thanks for the suggestion! b07dcce3cb6ad3b10a728f26177d49eba4620018
