### ISSUE TITLE
Recording disconnected RDP sessions

### ISSUE THREAD

**Issue by ciaranj** [rdp/screen-capture-recorder-to-video-windows-free#7]
Hi! Is it possible to record _disconnected_ remote desktop sessions with this driver ?  (Server 2008 R2)  The driver functions beautifully [both the shipped java tools and ffmpeg] when I'm connected to the remote session.  But if I disconnect (not logout, disconnect) the recorded session is 'black'.  

Is this a fundamental limitation of directshow or something that I'm doing wrong that I can work around with some awesome configuration options?

**Comment by rdp** [comment]
for followers, if you're using a hyper-V instance, from the mailing list: "This appears to be windows 8.1 RDP client behavior. It closes GUI session when minimized. I found a workaround by not connect to vm through mstsc client directly but from hyper-v manager. Thus I can minimize the window and GUI session stays alive."
