### ISSUE TITLE
capture_mouse_default_1 registry key has no effect when running as local SYSTEM account

### ISSUE THREAD

**Issue by ccc-tomr** [rdp/screen-capture-recorder-to-video-windows-free#70]
Awesome SW!

I use it a lot but recently found one minor bug:

The status (0 or 1) of the registry key 'capture_mouse_default_1'  doesn't disable mouse grabbing when screen-capture-recorder is running within the local SYSTEM account. I.e. in order to grab the login or screensaver screen as part of a remote desktop solution.

If screen-capture-recorder is running as a regular user account or as admin, the 'capture_mouse_default_1' key influences the mouse capturing correct.

**Comment by rdp** [comment]
interesting, must be because I use "HKCU" (current user) for the registry I
read from...the reason for that is that it is writable "without special
permissions" for the logged in user.
Alternative suggestion?

**Comment by ccc-tomr** [comment]
Yea, that might be it. I am not a big registry key expert but I wonder whether HKLM is a better place to put screen-capture-recorder's keys.

**Comment by ccc-tomr** [comment]
You were right.

After some googling about where a local system account reads out registry keys, I found this: 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/cef6584d-d05e-4510-a7c2-7ab529c303f9/setting-user-registry-keys-hkcu-from-a-local-system-account-service?forum=vcgeneral

I did a little experiment: 
Adding a capture_mouse_default_1 DWORD key to HKEY_USERS/.DEFAULT/Software/screen-capture-recorder, this key DOES influence the capture of the mouse when running screen_capture_recorder as local system account. 

Problem solved, closing...

**Comment by rdp** [comment]
Nice!
