### ISSUE TITLE
multiple displays ?

### ISSUE THREAD

**Issue by ccc-tomr** [rdp/screen-capture-recorder-to-video-windows-free#71]
IS multiple displays supported ? I can't find any parameters in the screen-capture-recorder registry that would allow me to grab from anything other than the 'primary display' but I have seen some mentioning of multiple displays in the code. 

If it is not implemented, how would I go about it ? Happy to work on that.

tomr

**Comment by rdp** [comment]
It would be possible to add this feature (today I just tell people to input the coordinates of the monitor they want to target :)

**Comment by ccc-tomr** [comment]
Good point, Thanks ! Following your advice I edited the registry keys 'start_x' and 'capture_width' and it worked. Now I can stream my PC's 2nd 'fake display' to another laptop and increase my pixel real estate using an old laptop or a tablet.

See also image attached (it shows grabbing desktop in between the 2 displays and streaming int into a browser) .

Since this addresses what I need, closing the issue...

![2nd display](https://cloud.githubusercontent.com/assets/6903627/14287327/912b6e2e-fb0f-11e5-8ca5-344b1bf7527e.png)
