### ISSUE TITLE
How i might use it with ffmpeg "From box"

### ISSUE THREAD

**Issue by sliterok** [rdp/screen-capture-recorder-to-video-windows-free#74]
Or there is no ways of doing it?

**Comment by rdp** [comment]
what is the ffmpeg from box?

**Comment by sliterok** [comment]
I meant to use screen-capture-recorder-to-video-windows-free with ffmpeg, from box. Like just extract some dll's right to ffmpeg.exe and start recording.

**Comment by rdp** [comment]
there is gdigrab "built in" to ffmpeg which may be interesting to you (in
place of screen-capture-recorder but doesn't have a virtual-audio-capturer
equivalent).
You can extract dll's alongside it but you need to register them as an
administrator first before you can use them...FWIW.

**Comment by sliterok** [comment]
Im making sort of... ffmpeg recording gui.
if i use webm as output of gdigrab it does everything... Strange. Like chaning colors in Chrome, or not even playing in mpc-hc.

**Comment by rdp** [comment]
is that a gdigrab thing or a webm thing (hint: possibly webm thing, or
maybe what pixel format it is using underneath...)

**Comment by sliterok** [comment]
I didn't find any pixel_format parameter, i could change in options of gdigrab, so... No idea.
Btw gdigrab outputs to .mp4 just fine.

**Comment by rdp** [comment]
https://www.google.com/search?q=ffmpeg+webm+html5&ie=utf-8&oe=utf-8 may be
interesting in terms of getting a webm to work, but I don't know much past
that.
GL!
-roger-

**Comment by rdp** [comment]
startlingly, if you know the CLSID you can target a dll and use that without registering the dll at all.  I've never tried it though, gl!
