### ISSUE TITLE
poor result on windows 10 no java?

### ISSUE THREAD

**Issue by rdp** [rdp/screen-capture-recorder-to-video-windows-free#75]
gah!

**Comment by axcelleria** [comment]
Hello, I trying to capture video with this command:

> ffmpeg -f dshow -framerate 30 -rtbufsize 512k -i audio="virtual-audio-capturer":video="screen-capture-recorder" d:\record.flv

Video frame rate seem set to 30 fps as expected, dimension 1366x768 px. but video bit-rate output only 200kbps. The video pixelate looks really bad. Am i missing something here?

**Comment by rdp** [comment]
probably need to specify a target bitrate for the video, the default maybe
is too small, GL!

**Comment by axcelleria** [comment]
Sample command line please?

**Comment by rdp** [comment]
b:v here
https://trac.ffmpeg.org/wiki/Encode/H.264

**Comment by axcelleria** [comment]
Wow, Thanks works like charms!

**Comment by rdp** [comment]
Got "better" results now, FWIW :)
