### ISSUE TITLE
Can I use this in C# application

### ISSUE THREAD

**Issue by rover886** [rdp/screen-capture-recorder-to-video-windows-free#76]
Hello,

I am developing an desktop capturing application in C#.NET. While searching for source filter I come to know about this screen capture filter. I gone through `README.adoc`. Before start using this in my application I wanted to know about following things:
1. Can I use only screen capture filter in c# application?
2. Do I still required to install JRE on development and client machines?
3.  How I can register this filter (`regasm` or `regsvr32`)? What will be the CLSID?

**Comment by rdp** [comment]
You can if your c# app uses directshow, or calls out to ffmpeg.exe (which
uses directshow).
no JRE required.
You register it like (administrator)
regsvr32 dll_name.dll
and
regsvr32 /u dll_name.dll (at uninstall time).  You just list the dll name
not the CLSID.
Cheers!

**Comment by rover886** [comment]
@rdp thanks for your reply. Yes my apllication is having directshow dll in reference.

I asked CLSID for the purpose of using it in c# code, just to create instance of filter and adding it into graph but anyways i will find CLSID (guid) from graphstudio.

One last doubt does this filter require any specific VC++ runtime version?

**Comment by rdp** [comment]
Today it does require MSVC 2010 runtime.
I suppose you could use the CLSID I usually use the IEnumMoniker stuff
myself.
Cheers!
