### ISSUE TITLE
issue about screen-capture-recorder-to-video color

### ISSUE THREAD

**Issue by hd16861686** [rdp/screen-capture-recorder-to-video-windows-free#79]
From screen-capture-recorder-to-video preview  I can see the text color is blue, 
but actually it is red.

snapshot can not uploaded :( ...

I used the screen-capture-recorder-to-video latest version

**Comment by rdp** [comment]
Which text color? Maybe post a snapshot to imgur
Cheers!

**Comment by hd16861686** [comment]
![_20160713194540](https://cloud.githubusercontent.com/assets/12622342/16908336/4088ab22-4cfd-11e6-95a5-aa05b256121e.png)

snapshot uploaded, please help to check~

**Comment by rdp** [comment]
odd. Can you repro it with ffmpeg to take a screen shot?
ffmpeg -f dshow -i video=screen-capture-recorder out.jpg

**Comment by hd16861686** [comment]
yes, from

**Comment by hd16861686** [comment]
yes, the color in out.jpg is OK,
ffmpeg -f dshow -i video=screen-capture-recorder out.jpg
maybe my microSIP preview has some problem. I'll check it 
thanks~!

**Comment by rdp** [comment]
no problem
