### ISSUE TITLE
Vlc 2.0 crashes when recording lord of the rings online with both screen-capture-recorder and virtual-audio-capture active

### ISSUE THREAD

**Issue by brancoliticus** [rdp/screen-capture-recorder-to-video-windows-free#8]
My system is win7 64 bit .
With a video quality of 800 kbps and audio at 2 channel , 128 kbps and 44100 sample rate I was having video quality issues , so I went for 1 channel , 11025 and 64 kbps . I try to do online encoding on 3 cores with the game on the other core .  The quality is ok when it works . Trouble is that when the game (or other processes ?) does some loading I belive , the whole setup crashes in the following way : out of 3 cores encoding activity stops except on 1 , vlc continues to work fine doing playback of videos stores on disk , when I close vlc the window closes fine but the process remains active , with >300MB of memory held and I have to kill it in task manager .
I also have a vlc log record from pressing start through the crash and some more stuff that I did in the vlc ui .
If you could think of a reason for the crash or tell me how I may be able to investigate this further I would apreciate it .

See https://gist.github.com/1984842 for the log file .

**Comment by rdp** [comment]
closing no response...
