### ISSUE TITLE
why bitblt took 25.31 ms in win 10 and 1920X1080 resolution?

### ISSUE THREAD

**Issue by luckywan** [rdp/screen-capture-recorder-to-video-windows-free#80]
hi,rdp.
why bitblt took 25.31 ms in win 10 and 1920X1080 resolution? how to optimize it?
i test it,every frame interval i got is about 33-45 ms,i need every frame interval is 16 ms,do you have any ideas?
the following is my log.

Frame365 -> 15:39:55.156
Frame366 -> 15:39:55.189
Frame367 -> 15:39:55.223 
Frame368 -> 15:39:55.254
Frame369 -> 15:39:55.288
Frame370 -> 15:39:55.325
Frame371 -> 15:39:55.370

thank you very much!

**Comment by rdp** [comment]
There is a capture speed benchmarking program in there too, care to run it
(good luck finding in windows 10, it is called "benchmark ...")

**Comment by rdp** [comment]
closing no response...
