### ISSUE TITLE
Using GitHub releases?

### ISSUE THREAD

**Issue by kirbyfan64** [rdp/screen-capture-recorder-to-video-windows-free#85]
It seems you started using SourceForge around 2011 or 2012 (too lazy to look through the full set of commit logs). Since then, GitHub has added [releases](https://github.com/blog/1547-release-your-software), which are basically the same thing, but no ads and faster downloads.

Also, I'm sitting here like an idiot, staring at your username and wondering *where have I seen this before?*, until I saw your Crystal repositories. ;)

**Comment by rdp** [comment]
OK I'll keep those in mind for my next release!
And if you've found me using crystal whoa, that's only a recent fling LOL.
Good to hear from you.
-roger-

**Comment by rdp** [comment]
I tried it out, seems it works well now, thank you! b07dcce3cb6ad3b10a728f26177d49eba4620018
