### ISSUE TITLE
i need to place logo on upper right corner of stream

### ISSUE THREAD

**Issue by lahela223** [rdp/screen-capture-recorder-to-video-windows-free#86]
hi rdp
i would like to know is it possible a png logo on video stream while its recording.?
is there any ffmpeg command which can do that or from within filter code can we apply png logo
please advice?
thankyou

**Comment by rdp** [comment]
overlay ffmpeg filter?

**Comment by lahela223** [comment]
ya i initially thought there might be some way in the screen capture recorder code just before its sending screen image to graph filter we can modify that image and draw some png image on it. i am not sure if thats possible from the code it self? yes else ffmpeg filter to put overlay? what paramaeter needs to be added to command

**Comment by kirbyfan64** [comment]
Did you try Googling it?

http://stackoverflow.com/a/10920872/2097780

Try:

```
ffmpeg -f dshow -i video="screen-capture-recorder":audio="virtual-audio-capturer" -i MYLOGO.jpg -filter_complex "overlay=W-w-5:5" -y "C:\Users\developer\Documents\output.mp4"
```

Change the *5*s to something else if you want it to be farther/closer.

**Comment by lahela223** [comment]
great thanks. wondering if you can add the overlay feature in the filter  it self? will be nice feature
may be some more registry key LogoPath and modify code to draw that image on screen image?

**Comment by rdp** [comment]
I try not to add features if they can exist outside of it...and yours is
the first request to do so so it's not a hugely in demand feature ? :)

**Comment by lahela223** [comment]
thankyou :) is there any way i can send you email?

**Comment by rdp** [comment]
rogerdpack@gmail.com

**Comment by rdp** [comment]
I'm closing this until more demand, until then use the ffmpeg overlay filter :)
