### ISSUE TITLE
Multiplexing data stream and video stream 

### ISSUE THREAD

**Issue by Palak92** [rdp/screen-capture-recorder-to-video-windows-free#90]
Is there any way to mux data stream and video stream in FFMPEG?

**Comment by rdp** [comment]
This is more of an ffmpeg question, but yeah, you just do two inputs like
ffmpeg -i audio -i video output_here see also
https://trac.ffmpeg.org/wiki/Map if you want to pick out particular inputs
to an output

**Comment by Palak92** [comment]
I can mux audio and video stream but not data stream and video stream. Here`s console command
`ffmpeg -i out.mp4 -i data.txt -map 0:0 -map 1:0 -c:v copy -c:d copy outputMerged.mp4`

Output:
```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.73.100
  Duration: 00:00:23.00, start: 0.000000, bitrate: 454 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1920x1080, 453 kb/s, 10 fps, 10 tbr, 10240 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, tty, from 'data.txt':
  Duration: 00:00:00.04, bitrate: 22 kb/s
    Stream #1:0: Video: ansi, pal8, 640x400, 25 fps, 25 tbr, 25 tbn, 25 tbc
File 'outputMerged.mp4' already exists. Overwrite ? [y/N] y
[mp4 @ 00000000030501a0] Could not find tag for codec ansi in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
```
What are supporeted codecs for data stream?

**Comment by rdp** [comment]
OK yeah I know nothing about data streams, maybe ask on ffmpeg-user mailing
list, good luck!
