### ISSUE TITLE
Can't use screen-capture-recorder and virtual audio capturer

### ISSUE THREAD

**Issue by viktae** [rdp/screen-capture-recorder-to-video-windows-free#93]
Hello!

I'm using ShareX and when I'm using screen-capture recorder and/or virtual audio capturer, I get this error
`IAudioCaptureClient::setup failed[dshow @ 00000000025d3600] Could not run graph (sometimes caused by a device already in use by other application)
video=screen-capture-recorder:audio=virtual-audio-capturer: I/O error`

I've downloaded the latest version of SCR, tried to use it without Sharex. When i'm stopping the audio recording with virtual-audio-capturer, my window freezes and I get no file. https://i.imgur.com/kdfXzqC.png  

But when I'm using something else (like my mic), everything's fine.

Need help please 😢 

Thanks!

**Comment by rdp** [comment]
video only work?

**Comment by viktae** [comment]
Both of them aren't working :(

**Comment by rdp** [comment]
In isolation they both don't work? You should at the least get a different
error message if you only do video...

**Comment by viktae** [comment]
Yup! Sorry for the late answer.
Video only: https://pastebin.com/1RYsbvHt
Sound only: https://pastebin.com/VnT8uM7j
Video and another sound source (like my mic): https://pastebin.com/pKJ2B7mN

**Comment by rdp** [comment]
Guess the problem is just with virtual audio...hmm...is this some kind of
VPN or a "real" box?

**Comment by viktae** [comment]
Yup! You were right... "is this some kind of vpn" about what? 
Anyways I suppose I can use the Realteak audio capturer... Thanks :)
