### ISSUE TITLE
How to disable/enable stream desktop?

### ISSUE THREAD

**Issue by vsile** [rdp/screen-capture-recorder-to-video-windows-free#94]
I've installed screen-capture-recorder and run "C:\Program Files\Screen Capturer Recorder\configuration_setup_utility\generic_run_rb.bat" stream_desktop_p2p.rb
It works! I can see my desktop on https://www.onlinemictest.com/webcam-test/.

How to disable stream desktop?
My desktop is streamed even after reboot!

**Comment by rdp** [comment]
Probably they're just showing you an old image of when you were previously streaming it.

**Comment by vsile** [comment]
No.
I tested streaming on Skype (my computer doesn't have any web cam). And Skype shows my Desktop!
I can't disable it!
What is the streaming process name? How can I find it in task manager?

**Comment by rdp** [comment]
OK hmm...yeah maybe you can turn it off in skype?

**Comment by rdp** [comment]
I think the only fix for skype is to uninstall it

**Comment by rdp** [comment]
closing since no feedback.

**Comment by KleaTech** [comment]
I'd like to reopen this. I need to be able to disable the service and I can't find a way to do it.
