### ISSUE TITLE
unsupported Java version: 9

### ISSUE THREAD

**Issue by denixx** [rdp/screen-capture-recorder-to-video-windows-free#96]
<pre>C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Screen Capturer Recorder\configure>"configure by setting specific screen capture numbers  Screen Capturer Recorder.lnk"
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.jruby.Main.<init>(Main.java:99)
        at org.jruby.Main.main(Main.java:193)
Caused by: java.lang.RuntimeException: unsupported Java version: 9
        at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1835)
        at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1585)
        ... 2 more</pre>

**Comment by rdp** [comment]
whoa cutting edge!

**Comment by denixx** [comment]
Yes, I know it's too fresh, but it's time to think about it. :)

**Comment by denixx** [comment]
Is there a Ruby unsupporting it?

**Comment by davidleon** [comment]
i tried to replace the jruby complete jar from the jruby website. it runs ok. but it doesn't kill the ffmpeg gracefully, thus the output can't be played. I think it's a better idea use python to implement the configure utility. Since it doesn't rely on java. so nothing like that could break the software itself.

**Comment by rdp** [comment]
kill, like on exit? Maybe file a separate issue about that...thanks!

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/83964535-121eb680-a8ae-11ea-87c6-46a89281678f.png)

@rdp This issue is still presented. As newer Java versions are today very common, can this repo be update to support the newest one? Or distribute Java 8 JRE with?

**Comment by mvorisek** [comment]
@denixx @rdp this issue is resolved in release https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11 , see https://github.com/rdp/screen-capture-recorder-to-video-windows-free/pull/132 , so it can be closed
