### ISSUE TITLE
How to capture mic+pc audio?

### ISSUE THREAD

**Issue by ZenoNiQ** [rdp/screen-capture-recorder-to-video-windows-free#98]
![sharex_2017-11-07_20-49-54](https://user-images.githubusercontent.com/1075196/32511709-43fe188c-c3fd-11e7-81c5-2deec6f7a174.png)
I am using this in ShareX. Is any possibilities to config it for micro capture too?

**Comment by rdp** [comment]
you want virtual-audio +mic?

**Comment by ZenoNiQ** [comment]
yeah

**Comment by rdp** [comment]
I'd suggest refile it here: https://github.com/ShareX/ShareX/issues there is at least an "amix" option that screen-capture-recorder uses (might be other options) that can be used...

**Comment by seeyouethan** [comment]
Usefule thanks
